name: CI

on:
  pull_request:
    branches:
    - sandbox
    - beta
    - beta-defi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: yarn

    - name: Codegen
      run: yarn codegen:sandbox
      if: github.head_ref == 'sandbox'

    - name: Codegen
      run: yarn codegen:beta
      if: github.head_ref == 'beta'

    - name: Codegen
      run: yarn codegen:beta-defi
      if: github.head_ref == 'beta-defi'

    - name: Build wasm
      run: yarn build:sandbox
      if: github.head_ref == 'sandbox'

    - name: Build wasm
      run: yarn build:beta
      if: github.head_ref == 'beta'

    - name: Build wasm
      run: yarn build:beta-defi
      if: github.head_ref == 'beta-defi'
